export interface Translations {
  nav: { dashboard: string; patients: string; newSession: string; aiAssistant: string; schedule: string; reports: string; logout: string }
  common: { save: string; cancel: string; delete: string; edit: string; back: string; loading: string; saving: string; search: string; noData: string; confirm: string; yes: string; viewDetail: string; addNew: string; export: string; print: string; today: string; tomorrow: string }
  dashboard: { title: string; activePatients: string; todaySchedule: string; aiAccepted: string; totalSessions: string; registered: string; allTime: string; weeklySchedule: string; scheduledSessions: string; noSchedule: string; createSchedule: string; upcomingSession: string; start: string; view: string; noSessionToday: string }
  patient: { title: string; registered: string; addPatient: string; searchPlaceholder: string; name: string; complaint: string; sessions: string; lastSession: string; status: string; active: string; new: string; age: string; noPatients: string; addFirst: string; newPatient: string; editPatient: string; patientInfo: string; fullName: string; gender: string; male: string; female: string; birthDate: string; phone: string; email: string; address: string; savePatient: string; medicalRecord: string; patientSince: string; nextSession: string; notScheduled: string; sessionHistory: string; totalSessionsCount: string; addSession: string; noHistory: string; addFirstSession: string; andBefore: string; tongueInspection: string; tongueColor: string; tongueCoating: string; tongueShape: string; tongueHumidity: string; aiSummary: string; syndromeIndication: string; aiRecommendation: string; noTCMDiagnosis: string; generalCondition: string; painScale: string; sleepQuality: string; dailyEnergy: string; overallProgress: string; improving: string; moderate: string; positive: string }
  session: { title: string; recorded: string; newSession: string; date: string; patient: string; chiefComplaint: string; points: string; pain: string; duration: string; detail: string; newSessionTitle: string; editSession: string; sessionInfo: string; patientLabel: string; dateTime: string; chiefComplaintLabel: string; chiefComplaintPlaceholder: string; tongueColor: string; tongueCoating: string; pulseQuality: string; painScaleLabel: string; additionalNotes: string; notesPlaceholder: string; acupuncturePoints: string; pickOrType: string; meridian: string; pointsUsed: string; pointsPlaceholder: string; tonguePicture: string; analyzedBy: string; saveSession: string; saveDraft: string; sessionDetail: string; sessionInfo2: string; tcmFindings: string; tcmDiagnosis: string; pointsUsedLabel: string; clinicalNotes: string; soapNotes: string; generateSoap: string; soapPlaceholder: string; aiRec: string; requestRec: string; analyzing: string; recPlaceholder: string; regenerate: string; mainPoints: string; aiSuggestion: string; fillComplaint: string; generateAI: string; generatingAI: string; prevSessions: string; tcmTip: string }
  schedule: { title: string; newSchedule: string; goToday: string; sessions: string; noSchedule: string; addSchedule: string; completed: string; upcoming: string; soon: string; cancelled: string; startSession: string; viewSession: string; cancelBtn: string; newScheduleTitle: string; editScheduleTitle: string; scheduleInfo: string; scheduleNote: string; visitReason: string; visitReasonPlaceholder: string; notes: string; notesPlaceholder: string; saveSchedule: string; duration: string }
  report: { title: string; exportCSV: string; activePatients: string; totalSessions: string; thisMonth: string; avgPerWeek: string; estimated: string; sessionsByMonth: string; last6Months: string; topComplaints: string; recentSessions: string; noData: string; patient: string; date: string }
  auth: { login: string; register: string; loginTitle: string; loginSubtitle: string; registerTitle: string; registerSubtitle: string; email: string; password: string; confirmPassword: string; doctorName: string; clinicName: string; loginBtn: string; registerBtn: string; noAccount: string; hasAccount: string; registerNow: string; signIn: string; loggingIn: string; registering: string; wrongCredentials: string; passwordMismatch: string; passwordTooShort: string }
  tongue: { title: string; dropzone: string; dropzoneHint: string; analyzeBtn: string; analyzing: string; savedLabel: string; uploadNew: string; uploadReplace: string; resultTitle: string; indications: string }
}
